import backend.data.Settings;
import backend.data.Controls;
import objects.handlers.Animation;
import objects.Alphabet;
import utils.Paths;
import utils.Tools;
import music.Conductor;
import music.Conductor.BPMChangeEvent;
using StringTools;
